**LOGISTIC REGRESSION**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [4]:
data=pd.read_excel("/content/drive/MyDrive/data.xlsx")

In [5]:
data.shape

(4244, 1001)

In [6]:
x=data.iloc[:,0:1000].values
y=data.iloc[:, 1000].values

In [7]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(
    x, y, test_size=0.25, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print (xtrain[0:10, :])

[[-1.01024436 -1.52958491 -0.74497572 ... -0.18399904  2.12169923
  -1.1096026 ]
 [-0.55891025 -0.10010184  0.60541203 ...  1.10347879 -0.67134155
   1.13840019]
 [-0.06036957 -0.82563648  0.98964954 ... -0.19341851 -0.73950423
   1.29353965]
 ...
 [-0.79105741  0.46483064  1.063703   ...  0.53949451 -0.9382912
  -0.19132343]
 [ 1.30473157 -0.95604364 -0.96047648 ...  0.6538837   0.16479929
   0.27474186]
 [ 0.82412266  0.16501304  1.04400927 ...  1.15934636  1.32237562
   0.62534148]]


In [9]:
#train the model
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [10]:
y_pred = classifier.predict(xtest)

In [11]:
#evaluation matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[ 82  26   0   0  16   2]
 [ 42  13   0   0   5   1]
 [  0   0 116 109   0   0]
 [  0   0 130 111   0   0]
 [ 21   7   0   0  13   1]
 [  0   0   0   0   0 366]]


In [12]:
from sklearn.metrics import accuracy_score

print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  0.6606974552309143


In [13]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(ytest, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[ 82  26   0   0  16   2]
 [ 42  13   0   0   5   1]
 [  0   0 116 109   0   0]
 [  0   0 130 111   0   0]
 [ 21   7   0   0  13   1]
 [  0   0   0   0   0 366]]

True Positives(TP) =  82

True Negatives(TN) =  13

False Positives(FP) =  26

False Negatives(FN) =  42


In [14]:
from sklearn.metrics import classification_report
print(classification_report(ytest, y_pred))

TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

              precision    recall  f1-score   support

           1       0.57      0.65      0.61       126
           2       0.28      0.21      0.24        61
           3       0.47      0.52      0.49       225
           4       0.50      0.46      0.48       241
           5       0.38      0.31      0.34        42
           6       0.99      1.00      0.99       366

    accuracy                           0.66      1061
   macro avg       0.53      0.52      0.53      1061
weighted avg       0.65      0.66      0.66      1061



**NAIVE BAYES**

In [16]:
import pandas as pd
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt # for data visualization purposes
import seaborn as sns # for statistical data visualization


In [18]:
print(data.head(),data.shape)

   -4.531595  -0.540618  -3.134417  -3.529312  -1.836297  -0.181893  \
0  -0.700899  -0.397490  -0.466649  -1.310355   0.883317   3.048673   
1  -2.747860   0.381365  -2.609185  -2.270594  -0.799617   2.579102   
2  -3.789822  -1.745898  -2.479308  -2.126775   0.895515  -0.258750   
3  -2.530930   0.794386  -0.999440  -2.038632   0.778601   3.664792   
4  -2.964701  -2.042924  -3.688849  -2.426204   0.242016   1.198319   

   -1.470371  -1.574101  -2.625470  -0.991899  ...  -0.760977  -2.516998  \
0   1.764694  -2.293167  -2.336639  -0.768678  ...  -1.685995  -2.139176   
1  -1.349673  -2.677015  -3.113053  -1.892761  ...  -1.384624  -3.375077   
2  -1.588678  -2.524915  -3.192336  -0.249713  ...  -0.648321  -2.332225   
3   1.148216  -0.423568  -1.666079   0.785010  ...  -0.343255  -1.126905   
4  -1.261189  -1.760720  -2.536230   0.774378  ...  -0.537261  -1.822949   

   -2.030744  -2.159886  -2.383677  -1.000806  -3.190276   0.977118  \
0  -4.317210  -2.027677  -2.459832  -1.882090

In [19]:
print(len(data))

4244


In [20]:
#x=data[:,[0:999]]
x=data.iloc[:,0:1000].values
y=data.iloc[:, 1000].values
#dataset.iloc[:, [2, 3]].values

In [21]:
print(x.shape,y.shape)

(4244, 1000) (4244,)


In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=9)

In [23]:

from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [24]:
from sklearn.naive_bayes import GaussianNB
nv = GaussianNB()
nv.fit(X_train,y_train)

from sklearn.metrics import accuracy_score

y_pred = nv.predict(X_test)

print(accuracy_score(y_test,y_pred))


0.6336866902237926


In [25]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
print(cm)

[[ 38  16   0   1  10   6]
 [ 28   8   0   0   1   7]
 [  0   0 100  96   0   0]
 [  0   0  81  85   0   0]
 [ 30  13   0   1  17   5]
 [ 10   3   0   0   3 290]]


In [26]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])



Confusion matrix

 [[ 38  28   0   0  30  10]
 [ 16   8   0   0  13   3]
 [  0   0 100  81   0   0]
 [  1   0  96  85   1   0]
 [ 10   1   0   0  17   3]
 [  6   7   0   0   5 290]]

True Positives(TP) =  38

True Negatives(TN) =  8

False Positives(FP) =  28

False Negatives(FN) =  16


In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

              precision    recall  f1-score   support

           1       0.36      0.54      0.43        71
           2       0.20      0.18      0.19        44
           3       0.55      0.51      0.53       196
           4       0.46      0.51      0.49       166
           5       0.55      0.26      0.35        66
           6       0.94      0.95      0.94       306

    accuracy                           0.63       849
   macro avg       0.51      0.49      0.49       849
weighted avg       0.64      0.63      0.63       849



In [28]:
# print classification accuracy

classification_accuracy = (TP + TN) / float(TP + TN + FP + FN)

print('Classification accuracy : {0:0.4f}'.format(classification_accuracy))

# print classification error

classification_error = (FP + FN) / float(TP + TN + FP + FN)

print('Classification error : {0:0.4f}'.format(classification_error))

# print precision score

precision = TP / float(TP + FP)


print('Precision : {0:0.4f}'.format(precision))

recall = TP / float(TP + FN)

print('Recall or Sensitivity : {0:0.4f}'.format(recall))

Classification accuracy : 0.5111
Classification error : 0.4889
Precision : 0.5758
Recall or Sensitivity : 0.7037


In [29]:

#plot ROC Curve
true_positive_rate = TP / float(TP + FN)


print('True Positive Rate : {0:0.4f}'.format(true_positive_rate))

false_positive_rate = FP / float(FP + TN)


print('False Positive Rate : {0:0.4f}'.format(false_positive_rate))

specificity = TN / (TN + FP)

print('Specificity : {0:0.4f}'.format(specificity))

True Positive Rate : 0.7037
False Positive Rate : 0.7778
Specificity : 0.2222


**KNN**

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [31]:
# Load your extracted features and labels here
# features should be a matrix where each row is a data point and each column is a feature
# labels should be a vector with the same number of rows as the features matrix, containing the label of each data point
num_rows = data.shape[0]
num_cols = data.shape[1]
print(num_rows)
print(num_cols)

features = data.iloc[:, :999]

labels = data.iloc[:, 1000]

4244
1001


In [32]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [33]:
# Scale the features to have zero mean and unit variance (this is recommended for KNN)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
# Train the KNN classifier
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [35]:
# Predict on the test set
y_pred = clf.predict(X_test)

In [36]:
# Evaluate the performance of the classifier using accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy score: {accuracy}")


Accuracy score: 0.6395759717314488


In [37]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
# y_true: true labels, y_pred: predicted labels
cm = confusion_matrix(y_test,y_pred)

In [38]:
# Print the confusion matrix
print(cm)

[[ 84  17   0   0   4   9]
 [ 28   7   0   0   0   5]
 [  0   0 102  91   0   0]
 [  0   0 100  97   0   0]
 [ 22   9   0   0   5   4]
 [ 13   2   0   0   2 248]]


In [39]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.57      0.74      0.64       114
           2       0.20      0.17      0.19        40
           3       0.50      0.53      0.52       193
           4       0.52      0.49      0.50       197
           5       0.45      0.12      0.20        40
           6       0.93      0.94      0.93       265

    accuracy                           0.64       849
   macro avg       0.53      0.50      0.50       849
weighted avg       0.63      0.64      0.63       849



In [40]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred,average=None)
recall = recall_score(y_test, y_pred,average=None)
f1 = f1_score(y_test, y_pred,average=None )

In [41]:
# Print the precision, recall, and F1 score
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Precision: [0.57142857 0.2        0.5049505  0.51595745 0.45454545 0.93233083]
Recall: [0.73684211 0.175      0.52849741 0.49238579 0.125      0.93584906]
F1 Score: [0.64367816 0.18666667 0.5164557  0.5038961  0.19607843 0.93408663]


In [42]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred,average='weighted')
recall = recall_score(y_test, y_pred,average='weighted')
f1 = f1_score(y_test, y_pred ,average='weighted')

In [43]:
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.6330876408285497
Recall: 0.6395759717314488
F1 Score: 0.6303481187120333


In [44]:
precision = precision_score(y_test, y_pred,average='macro')
recall = recall_score(y_test, y_pred,average='macro')
f1 = f1_score(y_test, y_pred ,average='macro')


print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.5298687991499517
Recall: 0.4989290596658978
F1 Score: 0.4968102813432124


In [45]:
#to go with the best n_neighbour count

from sklearn.model_selection import GridSearchCV
# Define the parameter grid to search over
param_grid = {'n_neighbors': [1, 3, 5, 7, 9]}

In [46]:
# Create a KNN classifier
clf = KNeighborsClassifier()

# Use GridSearchCV to find the best value of n_neighbors
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9]})

In [47]:
# Predict on the test set using the best estimator
y_pred = grid_search.best_estimator_.predict(X_test)

In [48]:
# Evaluate the performance of the classifier using accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy score: {accuracy}")

Accuracy score: 0.6619552414605419


In [49]:
precision = precision_score(y_test, y_pred,average='micro')
recall = recall_score(y_test, y_pred,average='micro')
f1 = f1_score(y_test, y_pred ,average='micro')

In [50]:
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.6619552414605419
Recall: 0.6619552414605419
F1 Score: 0.6619552414605419


In [51]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
# y_true: true labels, y_pred: predicted labels
cm = confusion_matrix(y_test,y_pred)

In [52]:

# Print the confusion matrix
print(cm)

[[ 90  10   0   0   2  12]
 [ 33   4   0   0   0   3]
 [  0   0 108  85   0   0]
 [  0   0  95 102   0   0]
 [ 30   1   0   0   2   7]
 [  8   0   0   0   1 256]]


In [53]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.56      0.79      0.65       114
           2       0.27      0.10      0.15        40
           3       0.53      0.56      0.55       193
           4       0.55      0.52      0.53       197
           5       0.40      0.05      0.09        40
           6       0.92      0.97      0.94       265

    accuracy                           0.66       849
   macro avg       0.54      0.50      0.48       849
weighted avg       0.64      0.66      0.64       849



**SVM**

In [54]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

In [55]:
num_rows = data.shape[0]
num_cols = data.shape[1]
print(num_rows)
print(num_cols)

features = data.iloc[:, :999]

labels = data.iloc[:, 1000]

4244
1001


In [56]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.25, random_state=42)

In [57]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
clf = svm.SVC(kernel='linear',probability=True)
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True)

In [59]:
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy score: {accuracy}")

Accuracy score: 0.6654099905749293


In [60]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
# y_true: true labels, y_pred: predicted labels
cm = confusion_matrix(y_test,y_pred)


In [61]:
# Print the confusion matrix
print(cm)

[[ 82  44   0   0  16   1]
 [ 36  14   0   0   2   0]
 [  0   0 132 103   0   0]
 [  0   0 118 125   0   0]
 [ 25   9   0   0  11   1]
 [  0   0   0   0   0 342]]


In [62]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.57      0.57      0.57       143
           2       0.21      0.27      0.24        52
           3       0.53      0.56      0.54       235
           4       0.55      0.51      0.53       243
           5       0.38      0.24      0.29        46
           6       0.99      1.00      1.00       342

    accuracy                           0.67      1061
   macro avg       0.54      0.53      0.53      1061
weighted avg       0.67      0.67      0.67      1061



In [63]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred,average='weighted')
recall = recall_score(y_test, y_pred,average='weighted')
f1 = f1_score(y_test, y_pred ,average='weighted')


In [64]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred,average=None)
recall = recall_score(y_test, y_pred,average=None)
f1 = f1_score(y_test, y_pred,average=None )

In [65]:
# Print the precision, recall, and F1 score
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: [0.57342657 0.20895522 0.528      0.54824561 0.37931034 0.99418605]
Recall: [0.57342657 0.26923077 0.56170213 0.51440329 0.23913043 1.        ]
F1 Score: [0.57342657 0.23529412 0.5443299  0.53078556 0.29333333 0.99708455]


In [66]:
precision = precision_score(y_test, y_pred,average='micro')
recall = recall_score(y_test, y_pred,average='micro')
f1 = f1_score(y_test, y_pred ,average='micro')


In [67]:
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.6654099905749293
Recall: 0.6654099905749293
F1 Score: 0.6654099905749293


In [68]:
precision = precision_score(y_test, y_pred,average='macro')
recall = recall_score(y_test, y_pred,average='macro')
f1 = f1_score(y_test, y_pred ,average='macro')

In [69]:
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.538687300446912
Recall: 0.5263155328800994
F1 Score: 0.5290423386753058


In [70]:
from sklearn.model_selection import KFold # import KFold
X = y_test
y =  y_pred
kf = KFold(n_splits=2) # Define the split - into 2 folds
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator
print(kf)
KFold(n_splits=2, random_state=None, shuffle=False)

KFold(n_splits=2, random_state=None, shuffle=False)


KFold(n_splits=2, random_state=None, shuffle=False)

**RANDOM FOREST**

In [71]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

In [72]:
x=data.iloc[:,0:1000].values
y=data.iloc[:, 1000].values

In [73]:
X_train, X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [74]:
rf = RandomForestClassifier(oob_score=True)

In [75]:
rf.fit(X_train,y_train)

RandomForestClassifier(oob_score=True)

In [76]:
rf.oob_score_

0.6456553755522828

In [77]:
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6183745583038869

In [78]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

              precision    recall  f1-score   support

           1       0.60      0.67      0.63       114
           2       0.00      0.00      0.00        40
           3       0.47      0.61      0.53       193
           4       0.47      0.34      0.39       197
           5       0.00      0.00      0.00        40
           6       0.80      1.00      0.89       265

    accuracy                           0.62       849
   macro avg       0.39      0.44      0.41       849
weighted avg       0.55      0.62      0.57       849



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**DECISION TREE**

In [79]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [80]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [81]:
features = data.iloc[:, :999]

labels = data.iloc[:, 1000]


In [ ]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split
(features, labels, test_size=0.3, random_state=1) # 70% training and 30% test

In [83]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

In [84]:
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)


In [85]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [86]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5512367491166078


In [87]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
# y_true: true labels, y_pred: predicted labels
cm = confusion_matrix(y_test,y_pred)

In [88]:
# Print the confusion matrix
print(cm)

[[ 42  27   0   2  12  31]
 [ 17  11   2   1   1   8]
 [  2   3  96  86   2   4]
 [  5   6  92  84   2   8]
 [ 14   8   1   1   6  10]
 [ 11  15   2   2   6 229]]


In [89]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           1       0.37      0.46      0.41        91
           2       0.28      0.16      0.20        70
           3       0.50      0.50      0.50       193
           4       0.43      0.48      0.45       176
           5       0.15      0.21      0.17        29
           6       0.86      0.79      0.83       290

    accuracy                           0.55       849
   macro avg       0.43      0.43      0.43       849
weighted avg       0.56      0.55      0.55       849



In [90]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

              precision    recall  f1-score   support

           1       0.37      0.46      0.41        91
           2       0.28      0.16      0.20        70
           3       0.50      0.50      0.50       193
           4       0.43      0.48      0.45       176
           5       0.15      0.21      0.17        29
           6       0.86      0.79      0.83       290

    accuracy                           0.55       849
   macro avg       0.43      0.43      0.43       849
weighted avg       0.56      0.55      0.55       849

